### PR TITLE
import extended statistics

### PR DESCRIPTION
**Pull request by lorban**
Extended statistics code, imported and adapted from the ehcache codebase.

### CODE REVIEW

**Comment by ljacomet** [comment]
test this please

**Comment by terracotta-org** [comment]
Can one of the admins verify this patch?

**Comment by ljacomet** [comment]
test this please

**Comment by ljacomet** [comment]
test this please

**Comment by ljacomet** [comment]
test this please

**Comment by ljacomet** [comment]
Sorry for the noise, configuring pull request building - done now

**Pull request merged**
